% Cell contents (by column)
% 1: String names
% 2: String lengths
% 3: Symbol cells
% 4: Duplicate symbols
% 5: Target coordinates
% 6: Target number ID
% 7: Original card coordinates
% 8: Array of cells for card data
    %Column corresponds to card number
    %Row 1: card symbol
    %Row 2: click counter 
    %Row 3: [start time, stop time] for each click
    %Row 4: destination cards, in order placed
% 9: Card last on target, moved?
%10: Original card coordinates for reset
%11: Target centers

if stringId{this,2} == 3
    DrawFormattedText(window, stringId{this,3}{1}, ... 
        stringId{this,11}{1}(1), stringId{this,11}{1}(2), 0);
    DrawFormattedText(window, stringId{this,3}{2}, ... 
        stringId{this,11}{2}(1), stringId{this,11}{2}(2), 0);
    DrawFormattedText(window, stringId{this,3}{3}, ... 
        stringId{this,11}{3}(1), stringId{this,11}{3}(2), 0);
elseif stringId{this,2} == 4
    DrawFormattedText(window, stringId{this,3}{1}, ... 
        stringId{this,11}{1}(1), stringId{this,11}{1}(2), 0);
    DrawFormattedText(window, stringId{this,3}{2}, ... 
        stringId{this,11}{2}(1), stringId{this,11}{2}(2), 0);
    DrawFormattedText(window, stringId{this,3}{3}, ... 
        stringId{this,11}{3}(1), stringId{this,11}{3}(2), 0);
    DrawFormattedText(window, stringId{this,3}{4}, ... 
        stringId{this,11}{4}(1), stringId{this,11}{4}(2), 0);
elseif stringId{this,2} == 5
    DrawFormattedText(window, stringId{this,3}{1}, ... 
        stringId{this,11}{1}(1), stringId{this,11}{1}(2), 0);
    DrawFormattedText(window, stringId{this,3}{2}, ... 
        stringId{this,11}{2}(1), stringId{this,11}{2}(2), 0);
    DrawFormattedText(window, stringId{this,3}{3}, ... 
        stringId{this,11}{3}(1), stringId{this,11}{3}(2), 0);
    DrawFormattedText(window, stringId{this,3}{4}, ... 
        stringId{this,11}{4}(1), stringId{this,11}{4}(2), 0);
    DrawFormattedText(window, stringId{this,3}{5}, ... 
        stringId{this,11}{5}(1), stringId{this,11}{5}(2), 0);
elseif stringId{this,2} == 6
    DrawFormattedText(window, stringId{this,3}{1}, ... 
        stringId{this,11}{1}(1), stringId{this,11}{1}(2), 0);
    DrawFormattedText(window, stringId{this,3}{2}, ... 
        stringId{this,11}{2}(1), stringId{this,11}{2}(2), 0);
    DrawFormattedText(window, stringId{this,3}{3}, ... 
        stringId{this,11}{3}(1), stringId{this,11}{3}(2), 0);
    DrawFormattedText(window, stringId{this,3}{4}, ... 
        stringId{this,11}{4}(1), stringId{this,11}{4}(2), 0);
    DrawFormattedText(window, stringId{this,3}{5}, ... 
        stringId{this,11}{5}(1), stringId{this,11}{5}(2), 0);
    DrawFormattedText(window, stringId{this,3}{6}, ... 
        stringId{this,11}{6}(1), stringId{this,11}{6}(2), 0);
elseif stringId{this,2} == 7
    DrawFormattedText(window, stringId{this,3}{1}, ... 
        stringId{this,11}{1}(1), stringId{this,11}{1}(2), 0);
    DrawFormattedText(window, stringId{this,3}{2}, ... 
        stringId{this,11}{2}(1), stringId{this,11}{2}(2), 0);
    DrawFormattedText(window, stringId{this,3}{3}, ... 
        stringId{this,11}{3}(1), stringId{this,11}{3}(2), 0);
    DrawFormattedText(window, stringId{this,3}{4}, ... 
        stringId{this,11}{4}(1), stringId{this,11}{4}(2), 0);
    DrawFormattedText(window, stringId{this,3}{5}, ... 
        stringId{this,11}{5}(1), stringId{this,11}{5}(2), 0);
    DrawFormattedText(window, stringId{this,3}{6}, ... 
        stringId{this,11}{6}(1), stringId{this,11}{6}(2), 0);
    DrawFormattedText(window, stringId{this,3}{7}, ... 
        stringId{this,11}{7}(1), stringId{this,11}{7}(2), 0);
end